version: 0.2    
phases:
  install:
    runtime-versions:
      dotnet: 8.0    
  pre_build:
    commands:
      - cd OpenScholar/OpenScholarApp
      # Restore NuGet packages, etc.
      - dotnet restore OpenScholarApp.sln
  build:
    commands:
      # Build your .NET project and output to a specific directory
      - dotnet build OpenScholarApp.sln
  post_build:
    commands:
      # Publish your .NET application to a specific folder
      - dotnet publish OpenScholarApp.sln --output ./site
      # Navigate to the output directory
      - cd site
      # Zip the contents of the publish directory into OpenScholarApp.zip
      - zip -r ../site.zip .
artifacts:
  files:
    - site.zip
    - aws-windows-deployment-manifest.json
  base-directory: OpenScholar/OpenScholarApp
