version: 0.2    
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS    
  pre_build:
    commands:
      - cd OpenScholar/OpenScholarApp
      # Restore NuGet packages, etc.
      - dotnet restore OpenScholarApp.sln
  build:
    commands:
      # Build your .NET project and output to a specific directory
      - dotnet build OpenScholarApp.sln --configuration Release
  post_build:
    commands:
      # Publish your .NET application to a specific folder
      - dotnet publish OpenScholarApp.sln --configuration Release --output ./build_output
artifacts:
  files:
    - '**/*'
  base-directory: 'OpenScholar/OpenScholarApp/build_output'
