version: 0.2    
phases:
  install:
    runtime-versions:
      dotnet: 8.0    
  pre_build:
    commands:
      - cd OpenScholar/OpenScholarApp
      # Restore NuGet packages, etc.
      - dotnet restore OpenScholarApp.sln
  build:
    commands:
      # Build your .NET 7 project
      - dotnet build OpenScholarApp.sln --configuration Release
artifacts:
  files:
    # Specify the files and directories to include in the build artifacts
    - '**/*'
  base-directory: 'build_output/'
