version: 0.2    
phases:
  install:
    runtime-versions:
      dotnet: 8.0    
  pre_build:
    commands:
      - cd OpenScholar/OpenScholarApp
      # Restore NuGet packages, etc.
      - dotnet restore OpenScholarApp.sln
  build:
    commands:
      # Build your .NET project and output to a specific directory
      - dotnet build OpenScholarApp.sln --configuration Release
  post-build:
    commands:
      # Publish your .NET application to a specific folder
      - dotnet publish --configuration Release --output ./
artifacts:
  files:
    - '**/*'